installCRDs: true

# Optional: Set default issuer for ingress annotations
# You can configure a ClusterIssuer separately after install
extraArgs:
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53

# Disable telemetry
global:
  telemetry:
    enabled: false

# Optional: if you want to use a custom namespace or cluster-wide resources
prometheus:
  enabled: false

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi