controller:
  replicaCount: 1

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443

  service:
    enabled: false

  ingressClassResource:
    name: nginx
    enabled: true
    default: true

  metrics:
    enabled: true

  admissionWebhooks:
    enabled: true
    patch:
      enabled: true

  extraArgs:
    enable-ssl-passthrough: ""

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  nodeSelector: {}
  affinity: {}